-- 1. Create table for task evidence
CREATE TABLE IF NOT EXISTS task_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_code TEXT NOT NULL,
    task_id TEXT NOT NULL,
    image_url TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable RLS
ALTER TABLE task_evidence ENABLE ROW LEVEL SECURITY;

-- 3. Create policies for public/anon access (since we use custom auth)
CREATE POLICY "Enable read access for all users"
ON task_evidence FOR SELECT
USING (true);

CREATE POLICY "Enable insert access for all users"
ON task_evidence FOR INSERT
WITH CHECK (true);

CREATE POLICY "Enable delete access for all users"
ON task_evidence FOR DELETE
USING (true);

-- STORAGE POLICIES (Run these in Storage > Policies)
-- Bucket: 'evidence'
-- Policy: Give anon/public access to SELECT, INSERT, UPDATE
