-- Create broadcasts table
create table public.broadcasts (
  id bigint generated by default as identity primary key,
  message text not null,
  is_active boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.broadcasts enable row level security;

-- Policies
create policy "Public can read active broadcasts"
  on public.broadcasts for select
  to anon, authenticated
  using (true);

create policy "Only authenticated can update broadcasts"
  on public.broadcasts for all
  to authenticated
  using (true)
  with check (true);

-- Insert initial row
insert into public.broadcasts (message, is_active)
values ('Chúc mừng năm mới Xuân Bính Ngọ 2026! 🌸', true);
